[package]
name = "playground"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
automat-core = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true